---
title: "Draft"
author:
  name: Christian Hicks
  url: https://github.com/hicks017
bibliography: resources/references.bib
csl: resources/reference_style_vancouver.csl
format:
  html:
    embed-resources: true
    df-print: kable
    toc: true
    toc-depth: 3
    code-fold: true
    date: 2025-04-13
    date-modified: last-modified
description: An analysis of rule changes recent to 2025 Major League Baseball.
editor: visual
---

## Background

The year 2020 brought big changes to the world, such as how Major League Baseball (MLB) is played. In fact, the five-year span of 2019-2023 had the largest number of rule changes in any other five-year span of MLB history [@inc_mlb_nodate]. These efforts aimed to reduce the length of games, increase scoring, preserve player safety, and increase viewership. The introduction of the three‑batter minimum for relief pitchers in 2020 sought to remove one‑ and two‑batter “specialist” relievers and thereby reduce the number of pitching changes that prolong games [@noauthor_these_nodate; @noauthor_three-batter_nodate; @noauthor_three-batter_nodate-1]. In the same year the league introduced the infamous "Manfred Man", an extra‑innings runner on second base to promote earlier scoring and shorten games stuck in a stalemate [@noauthor_designated_nodate; @noauthor_designated_nodate-3; @noauthor_ghost_2023]. The universal designated hitter eliminated the pitcher’s plate appearance and intended to boost offensive production [@noauthor_designated_nodate-1; @noauthor_designated_nodate-2; @noauthor_new_nodate].

In 2023, MLB continued the offensive and safety initiatives. Bases were increased in size from 15″ to 18″ to shorten the distance between bags, with the dual-purpose of encouraging more stolen‑base attempts and reducing dangerous collisions [@noauthor_base_nodate; @noauthor_base_nodate-1]. The pitch clock and disengagement policy were also deployed to accelerate the game tempo [@noauthor_pitch_nodate; @noauthor_pitch_nodate-1; @noauthor_pitch_nodate-2; @noauthor_balk_nodate; @schofield_pitch_2023]. Finally, restrictions on defensive positioning prevented "the shift", an extreme alignment that countered pull-hitters and reduced their batting‑average‐on‐balls‐in‐play (BABIP) [@noauthor_defensive_nodate; @noauthor_defensive_nodate-1].

While each of these rule changes intends to improve the MLB viewing experiences, their real-world effects require systematic and independent quantification. This analysis leverages publicly available pitch-by-pitch, play-by-play, and other game day datasets to measure key metrics before and after each rule's implementation. Comparing metrics with pre- and post-rule windows aims to provide empirical evidence on the efficacy of MLB's recent innovations and inform future decision-making in professional baseball.

## Methods

**Notes**

Observation window

-   2014-2024

-   Used year of implementation for each rule to determine pre-rule and post-rule windows

-   Regular season games only

-   MLB teams only; No minor leagues

-   2020 including when using within-game metrics, excluded when using season-long metrics

Granularity of data

-   Game-level, inning-level, individual plays, and season-long as needed per metric.

Sources

-   MLB Stats API for all data

Outcomes

-   3-batter minimum: Number of pitchers used per game, number of pitching changes in the middle of an inning per game, proportion of games with at least one/two/three mid-inning pitching changes

-   Extra-innings baserunner: Number of extra innings required to complete a tied game at the 9th inning, number of runs scored during extra innings, number of batters needed before first run in extra innings, final inning in marathon games, total runs in marathon games, batters until first score in marathon games (marathons being those in the 95th percentile of game length by innings per season)

-   Universal designated hitter: Number of at-bats by pitcher position during pre-rule window versus number by DH position during post-rule window, on base percentage of pitcher position during pre-rule window versus percentage of DH position during post-rule window, and on-base-plus-slugging with same comparison

-   Base stealing / bigger bases / pitcher disengagement policy: Number of attempted steals by teams per season, success rate of steals by teams per season

-   Pitch clock and play duration: Length of individual plays, combined game duration (action time, excluding non-play time)

-   Defensive shift ban: Team BABIP stat across seasons, outcome of plays (hit, out, etc) when batter makes pull-side contact

Statistical analysis

-   Summarize each metric with mean (SD), median (IQR), and range.

-   Pre/post comparisons with two-sample t-tests (not paired because too many variables change such as players, coaches, schedules, weather). 95% confidence intervals for differences in means or proportions.

-   Exclusion of 2020 year when shortened season would affect team statistics.

Software and reproducibility

-   Python version 3.11.6

-   R version 4.4.3

-   Version control stored on GitHub repository containing all scripts and Docker files

Data licensing

-   All data are publicacly available via the free MLB Stats API

-   No personal player data or personally identifiable information were used

## References
